theme = "devys-dark"

[editor]
line-number = "relative"
mouse = true
completion-trigger-len = 1
auto-completion = true
auto-format = true
auto-save = true
auto-pairs = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["workspace-diagnostics", "version-control"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending"]

[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
max-depth = 10

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

# Main key bindings
[keys.normal]
# File operations
"C-s" = ":w"           # Save
"C-S-s" = ":wa"        # Save all
"C-q" = ":q"           # Quit
"C-S-q" = ":qa"        # Quit all

# Navigation
"C-p" = "file_picker"
"C-S-p" = "command_palette"
"C-f" = "global_search"

# Undo/Redo
"C-z" = ":u"           # Undo
"C-S-z" = ":U"         # Redo

# Devys AI bindings - Workspace commands
[keys.normal.space.a]
a = ":devys-ai-complete"     # AI auto-complete
p = ":devys-plan"            # Plan with AI
e = ":devys-edit"            # Edit with AI
r = ":devys-review"          # Review with AI
g = ":devys-grunt"           # Grunt tasks
x = ":devys-explain"         # Explain code
f = ":devys-fix"             # Fix errors
d = ":devys-docs"            # Generate docs
t = ":devys-test"            # Generate tests

# Context and model management
[keys.normal.space]
c = ":devys-context-view"    # View context
m = ":devys-model-select"    # Select model
s = ":devys-status"          # Show status
o = ":devys-optimize"        # Optimize context

# Enhanced goto with AI understanding
[keys.normal.g]
d = "devys:goto-definition"
r = "devys:goto-references"
i = "devys:goto-implementation"
t = "devys:goto-type-definition"
s = "devys:goto-symbol"

# LSP with AI enhancements
[keys.normal.space.l]
a = "code_action"
r = "rename_symbol"
f = "format_selections"
h = "hover"
d = "diagnostics_picker"
s = "symbol_picker"
S = "workspace_symbol_picker"

# Git integration
[keys.normal.space.g]
g = ":sh git status"
a = ":sh git add ."
c = ":sh git commit"
p = ":sh git push"
l = ":sh git log --oneline -10"
d = ":sh git diff"
b = ":sh git branch -v"

# Window/pane management
[keys.normal.space.w]
v = "vsplit"
s = "hsplit"
q = "wclose"
o = "wonly"
h = "jump_view_left"
j = "jump_view_down"
k = "jump_view_up"
l = "jump_view_right"

# Buffer management
[keys.normal.space.b]
b = "buffer_picker"
n = ":bn"
p = ":bp"
d = ":bd"
s = ":w"

# Search and replace
[keys.normal.space.s]
s = "global_search"
r = "search_selection"
R = "replace_selections_with_clipboard"

# Terminal integration
[keys.normal.space.t]
t = ":sh zellij action new-tab --layout default"
s = ":sh zellij action new-pane --direction down"
v = ":sh zellij action new-pane --direction right"

# Quick actions
[keys.normal]
"ret" = ["open_below", "normal_mode"]
"S-ret" = ["open_above", "normal_mode"]
"C-/" = "toggle_comments"
"C-d" = ["select_line", "delete_selection"]

# Insert mode bindings
[keys.insert]
"C-s" = ["normal_mode", ":w", "insert_mode"]
"C-z" = ["normal_mode", ":u", "insert_mode"]
"C-y" = ["normal_mode", ":U", "insert_mode"]

# AI-specific insert mode shortcuts
"C-space" = ["normal_mode", ":devys-ai-complete", "insert_mode"]
"A-p" = ["normal_mode", ":devys-plan", "insert_mode"]
"A-e" = ["normal_mode", ":devys-explain", "insert_mode"]

# Visual mode bindings
[keys.select]
"A-a" = ":devys-ai-complete"
"A-r" = ":devys-refactor"
"A-e" = ":devys-explain"
"A-f" = ":devys-fix"